<?php

declare(strict_types=1);

namespace MidgardWhmcs;

use Illuminate\Database\Capsule\Manager as Capsule;

/**
 * Programmatically creates and maintains WHMCS Configurable Options
 * for Midgard location and OS image selection at order time.
 *
 * Works with four WHMCS tables:
 *  - tblproductconfiggroups   (group container)
 *  - tblproductconfigoptions   (individual option definitions)
 *  - tblproductconfigoptionssub (dropdown choices)
 *  - tblproductconfiglinks     (group ↔ product links)
 */
final class ConfigOptionManager
{
    private const GROUP_NAME        = 'Midgard';
    private const OPT_LOCATION      = 'location_id';
    private const OPT_OS_IMAGE      = 'os_image_id';
    private const OPTION_TYPE_DROPDOWN = 1;

    /**
     * Create or update the Midgard configurable option group for a product,
     * syncing location and OS image sub-options from the catalog cache.
     */
    public static function syncForProduct(int $productId): void
    {
        if ($productId <= 0) {
            return;
        }

        $groupId = self::ensureGroupLinked($productId);

        $locations  = CatalogCache::getLocations();
        $osImages   = CatalogCache::getOsImages();

        self::syncOption($groupId, self::OPT_LOCATION, 'Location', $locations);
        self::syncOption($groupId, self::OPT_OS_IMAGE, 'OS Image', $osImages);
    }

    /**
     * Find or create the "Midgard" config group and link it to the product.
     *
     * @return int Group ID
     */
    private static function ensureGroupLinked(int $productId): int
    {
        $groupId = (int) Capsule::table('tblproductconfiggroups')
            ->where('name', self::GROUP_NAME)
            ->value('id');

        if ($groupId <= 0) {
            $groupId = (int) Capsule::table('tblproductconfiggroups')->insertGetId([
                'name'        => self::GROUP_NAME,
                'description' => 'Auto-generated by Midgard module — Location and OS Image selection',
                'hidden'      => 0,
            ]);
        }

        // Link group to product if not already linked.
        $exists = Capsule::table('tblproductconfiglinks')
            ->where('gid', $groupId)
            ->where('pid', $productId)
            ->exists();

        if (! $exists) {
            Capsule::table('tblproductconfiglinks')->insert([
                'gid' => $groupId,
                'pid' => $productId,
            ]);
        }

        return $groupId;
    }

    /**
     * Sync a single configurable option and its sub-options.
     *
     * @param int    $groupId    Config group ID
     * @param string $optionName Internal key (e.g. "location_id")
     * @param string $displayName Human-readable label (e.g. "Location")
     * @param array<int, array{id: int, label: string}> $items Catalog items
     */
    private static function syncOption(int $groupId, string $optionName, string $displayName, array $items): void
    {
        // Find or create the option definition.
        $optionId = (int) Capsule::table('tblproductconfigoptions')
            ->where('gid', $groupId)
            ->where('optionname', $optionName)
            ->value('id');

        if ($optionId <= 0) {
            $optionId = (int) Capsule::table('tblproductconfigoptions')->insertGetId([
                'gid'        => $groupId,
                'optionname' => $optionName,
                'optiontype' => self::OPTION_TYPE_DROPDOWN,
                'qtyminimum' => 0,
                'qtymaximum' => 0,
                'order'      => 0,
                'hidden'     => 0,
            ]);
        }

        // Build the desired set of sub-option values ("ID|Label").
        $desiredValues = [];
        foreach ($items as $item) {
            $id    = (int) ($item['id'] ?? 0);
            $label = trim((string) ($item['label'] ?? ''));
            if ($id > 0 && $label !== '') {
                $desiredValues[$id] = $id . '|' . $label;
            }
        }

        // Load existing sub-options.
        $existing = Capsule::table('tblproductconfigoptionssub')
            ->where('configid', $optionId)
            ->get(['id', 'optionname']);

        $existingById = [];
        foreach ($existing as $row) {
            $parsedId = self::parseIdFromSubOption((string) $row->optionname);
            if ($parsedId !== null) {
                $existingById[$parsedId] = [
                    'sub_id'      => (int) $row->id,
                    'optionname'  => (string) $row->optionname,
                ];
            }
        }

        // Upsert: add new, update changed labels.
        $sortOrder = 0;
        foreach ($desiredValues as $catalogId => $valueStr) {
            $sortOrder++;
            if (isset($existingById[$catalogId])) {
                if ($existingById[$catalogId]['optionname'] !== $valueStr) {
                    Capsule::table('tblproductconfigoptionssub')
                        ->where('id', $existingById[$catalogId]['sub_id'])
                        ->update([
                            'optionname' => $valueStr,
                            'sortorder'  => $sortOrder,
                        ]);
                } else {
                    Capsule::table('tblproductconfigoptionssub')
                        ->where('id', $existingById[$catalogId]['sub_id'])
                        ->update(['sortorder' => $sortOrder]);
                }
            } else {
                $newSubId = (int) Capsule::table('tblproductconfigoptionssub')->insertGetId([
                    'configid'   => $optionId,
                    'optionname' => $valueStr,
                    'sortorder'  => $sortOrder,
                    'hidden'     => 0,
                ]);

                // Add default $0 pricing for all currencies.
                self::addDefaultPricing($newSubId);
            }
        }

        // Delete sub-options that no longer exist in the catalog.
        $desiredIds = array_keys($desiredValues);
        foreach ($existingById as $catalogId => $info) {
            if (! in_array($catalogId, $desiredIds, true)) {
                Capsule::table('tblpricing')
                    ->where('type', 'configoptions')
                    ->where('relid', $info['sub_id'])
                    ->delete();
                Capsule::table('tblproductconfigoptionssub')
                    ->where('id', $info['sub_id'])
                    ->delete();
            }
        }
    }

    /**
     * Extract the numeric ID from an "ID|Label" sub-option value.
     */
    private static function parseIdFromSubOption(string $optionname): ?int
    {
        $pipePos = strpos($optionname, '|');
        if ($pipePos === false) {
            return null;
        }

        $idPart = trim(substr($optionname, 0, $pipePos));
        if (! ctype_digit($idPart)) {
            return null;
        }

        return (int) $idPart;
    }

    /**
     * Insert $0 pricing rows for a new sub-option across all currencies.
     */
    private static function addDefaultPricing(int $subOptionId): void
    {
        $currencies = Capsule::table('tblcurrencies')->get(['id']);

        foreach ($currencies as $currency) {
            Capsule::table('tblpricing')->insert([
                'type'         => 'configoptions',
                'currency'     => $currency->id,
                'relid'        => $subOptionId,
                'msetupfee'    => 0,
                'qsetupfee'    => 0,
                'ssetupfee'    => 0,
                'asetupfee'    => 0,
                'bsetupfee'    => 0,
                'tsetupfee'    => 0,
                'monthly'      => 0,
                'quarterly'    => 0,
                'semiannually' => 0,
                'annually'     => 0,
                'biennially'   => 0,
                'triennially'  => 0,
            ]);
        }
    }
}
